### ISSUE TITLE
Update PyPi version of django-mailgun

### ISSUE THREAD

**Issue by natemara** [BradWhittington/django-mailgun#15]
I see that the master branch of django-mailgun has support for python3 because it uses the `io` module instead of the `StringIO` module, but this change is not reflected in the newest version of django mailgun on PyPi.

**Comment by sdornan** [comment]
:+1:

**Comment by pydanny** [comment]
:+1:

**Comment by pydanny** [comment]
Until @BradWhittington has the time to look at this awesome project, I made a 'friendly fork' at https://github.com/pydanny/django-mailgun and released it at https://pypi.python.org/pypi/django-mailgun-redux.

Once @BradWhittington comes back, I'll stop maintenance of that project.

**Comment by ryneeverett** [comment]
@pydanny Are you using your fork with python3? See #21. I wasn't able to get master working with python3 without rolling back the latest PR, but perhaps I misdiagnosed the problem.

**Comment by pydanny** [comment]
I haven't had any unicode problems yet, but then again I haven't tried anything beyond ASCII. 

As we use this package in cookiecutter-django, I've let @mailgun know that it would be nice to have a maintained package. :smile:

**Comment by ryneeverett** [comment]
@pydanny It's not a unicode error, it's the fact that the latest commit uses the `unicode` builtin, which was removed in python3.

```py
>>> unicode
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'unicode' is not defined
```

**Comment by BradWhittington** [comment]
I've given @pydanny the keys to the repo and release rights on pypi, sorry I've been a blocker to progress on this... I haven't used this lib myself for a while, hopefully this helps move it forward.

**Comment by pydanny** [comment]
I did a 0.3.0 release yesterday. In the next day or so I will stand up a test suite so I can more quickly accept pull requests. Therefore I'm marking this as closed.
