### ISSUE TITLE
pip install problem in python 3

### ISSUE THREAD

**Issue by balavec** [BradWhittington/django-mailgun#16]
I used pip install django-mailgun to add the app to my Django project.
It seems the code in pip is not synced with github.

try:
    from cStringIO import StringIO
except ImportError:
    from StringIO import StringIO

**Comment by grindmodeon** [comment]
Having this issue also. Please fix this!

**Comment by zkanda** [comment]
This is fix in master. You can install it like this:
```bash
$ pip install git+git://github.com/BradWhittington/django-mailgun@master
```

**Comment by grindmodeon** [comment]
Cool, thanks so much. Will give that a shot. :)

Would there be a possibility to implement a way for emails to be queued using celery or something? So that the user request flow isn't affected on mailguns API response time? Any ideas?

**Comment by zkanda** [comment]
That's what I do, but here is not the right place to ask this as it's not related to the issue.
go to #django irc. Lot's of people there that could help you.

**Comment by sdornan** [comment]
:+1:

**Comment by pydanny** [comment]
This should no longer be an issue. Please reopen if problems continue.
