### ISSUE TITLE
Backend doesn't support CC and BCC

### ISSUE THREAD

**Issue by BradWhittington** [BradWhittington/django-mailgun#2]
Backend should support the CC and BCC headers http://documentation.mailgun.net/quickstart.html

**Comment by gamb** [comment]
+1

**Comment by WillNy3** [comment]
I fixed the issue, sort of. Check out my post on SO http://stackoverflow.com/questions/33486342/django-mailgun-bcc

**Comment by sandroden** [comment]
Is there a reason not to merge what has already been fixed?

Please note that it not only missing cc and bcc support: it is misinterpreting the recipients attribute. If you don't realize this you end up sending email to cc AND bcc in the To: field. That can be really embarassing!!! The suggested patch solves this issue also.

Please issue a new fixed release.

**Comment by jhancia** [comment]
Appreciate the fix. Can we please have a new pip release to incorporate the merged PR?  Thanks!

**Comment by EyePulp** [comment]
@pydanny or @bradwhittington Would you be able to bump the Pypi version to include this merged improvement?  Thanks, and thanks for the work on the module.  Fills a nice gap in mailgun's offerings.

**Comment by pydanny** [comment]
I just merged https://github.com/BradWhittington/django-mailgun/pull/39.

I'll see about putting out a PyPI bump today. That said, I've contacted Mailgun and their staff (@jseutter) so they can take responsibility fro the the package going forward.

**Comment by EyePulp** [comment]
Ah, perfect, and good thinking on getting MG to step up.  Thank you.
