### ISSUE TITLE
New Feature: support scheduled delivery

### ISSUE THREAD

**Issue by browniebroke** [BradWhittington/django-mailgun#20]
Mailgun has a feature [to schedule delivery of messages](http://blog.mailgun.com/tips-tricks-scheduling-email-delivery/) at a given date and time. All is needed is to pass an extra parameter to the Mailgun API call with the date.

That would be a nice to have, but could become quite a chunk as it would possibly need:

* New `send_scheduled_mail` wrapper
* Using a new `ScheduledEmailMessage` with `delivery_date` attribute (don't think monkey-patching a non-standard attribute on Django's `EmailMessage` is a clean solution)
* Update `MailgunBackend._send` to add this attribute to the API call with the correct format only if it's present in the `email_message`

Happy to implement it if agreed.

**Comment by pydanny** [comment]
Interesting idea. My only concern is that Django normally allows you to have only one email client specified. This would mean providing carefully documented instructions to the user on how to call the `ScheduledEmailMessage` client. Plus tests.

I'm game to look at a pull request if you want to write one. :smile:

**Comment by browniebroke** [comment]
Did a bit of testing at the time, but it seems the scheduling could only be done up to 3 days in the future, and we needed 1 week+ in my project. We ended up abandoning this idea, and I don't really have time for it anymore. 
Since no one else has shown interest in this feature, I'm closing this.
