### ISSUE TITLE
Unicode error

### ISSUE THREAD

**Issue by mousavian** [BradWhittington/django-mailgun#22]
Since "[All text is Unicode](https://docs.python.org/release/3.0.1/whatsnew/3.0.html#text-vs-data-instead-of-unicode-vs-8-bit)" in Python v>3.0 then [this line of code](https://github.com/BradWhittington/django-mailgun/blob/master/django_mailgun/__init__.py#L67) will throw an error says:
`name 'unicode' is not defined`

So, regarding to [this answer](http://stackoverflow.com/questions/19877306/nameerror-global-name-unicode-is-not-defined-in-python-3#), I guess `unicode` function should be changed to `str` or `decode()`

**Comment by ryneeverett** [comment]
FYI, I opened #21 for this issue. If you look at the commit history the fix for python2 unicode issues broke python3.

**Comment by pydanny** [comment]
I believe this is fixed. Please confirm!

**Comment by pydanny** [comment]
Closing this. If this is still a problem, please reopen.
