### ISSUE TITLE
Wheel file on pypi is broken

### ISSUE THREAD

**Issue by wmsmith** [BradWhittington/django-mailgun#28]
The wheel package of the latest version on pypi (https://pypi.python.org/packages/2.7/d/django-mailgun/django_mailgun-0.7.0-py2.py3-none-any.whl#md5=f9f840324bee50550cfe4278ad29b5e1) has an __init__.py that contains an older version of django-mailgun.  When our app tries to send emails, Django uses this version of the backend which has none of the latest changes, and not the updated version of the code in django_mailgun.py.  Removing the __init__ file solves the issue, as then Django uses django_mailgun.py.

Using Django 1.8.4, django-mailgun 0.7.0

**Comment by pydanny** [comment]
Confirmed. Doing patch release right now.

**Comment by wmsmith** [comment]
Thanks!

**Comment by pydanny** [comment]
The problem appears to be that my version of `setuptools`  doesn't properly clean up after itself, specifically in the `build` directory. So legacy folders with code remain. Yuck. 

In any case, I've deleted the old `build` directory and cut a 0.7.1 release at https://pypi.python.org/pypi/django-mailgun.

**Comment by pydanny** [comment]
Marking this as closed.
