### ISSUE TITLE
Tests failing for Python 3

### ISSUE THREAD

**Issue by pydanny** [BradWhittington/django-mailgun#38]
I wanted to do a new release. Alas, Python 3 is broken - I should have run tests on all versions of Python before accepting pull requests . For that matter, I should have set up continuous integration. This needs to be fixed before I'll issue a release. 

**Problem:** I simply don't have the free time to support a library for a commercial endeavor (@mailgun).

If someone can get the tests working properly for Python 2.7 and Python 3.5 I'll issue a release.In the meantime, the project is on hold.

**Comment by sigmavirus24** [comment]
@pydanny thanks for maintaining this for as long as you have. I'm going to reach out internally tomorrow to see if we have anyone who can spare some cycles to get this into a working state and help out here long term. Cheers.

**Comment by juraisa** [comment]
Howdy, can you clarify how these tests are being run, when I try to run py.test against the github pull I see errors even on python2, not that familiar with django applications but happy to work on fixing the python versioning issues if I had a useable testbed

**Comment by sigmavirus24** [comment]
@juraisa I would suspect that you could follow this to roughly emulate what happens on [Travis](https://github.com/BradWhittington/django-mailgun/blob/master/.travis.yml):

- `virtualenv -p (python-version) django-mailgun-(py-version)` (e.g., `virtualenv -p python2.7 django-mailgun-py27`)
- activate the virtualenv (e.g., `source django-mailgun-(py-version)/bin/activate`)
- `pip install -r requirements-test.txt`
- `coverage run --source spam runtests.py`

**Comment by sigmavirus24** [comment]
Although that might not be true since I can't find `runtests.py`. Maybe [`make test`](https://github.com/BradWhittington/django-mailgun/blob/master/Makefile)?

**Comment by jseutter** [comment]
I fixed a python 3 incompatibility, PR here: https://github.com/BradWhittington/django-mailgun/pull/39

juraisa has issues with running the tests because some files appear to be missing.  Can someone with access to Travis check to see if the files exist on the server but aren't checked in? Specifically

requirements-test.txt
runtests.py

**Comment by pydanny** [comment]
@jseutter Apologies. On another machine I had the pieces to run the tests, but that machine is gone. 😩

**Comment by pydanny** [comment]
This project is unsupported. Please use https://github.com/anymail/django-anymail instead.
