### ISSUE TITLE
Given this isn't supported, can you please update the pypi page for it, or pull the package?

### ISSUE THREAD

**Issue by yaleman** [BradWhittington/django-mailgun#45]
It would have saved me a few hours of troubleshooting what I thought was my problem...

**Comment by Shelagh-Lewins** [comment]
Same comment from me! I gave this package a try, found I got an error, and also that using mailgun with Django isn't very hard without it. See for example https://simpleisbetterthancomplex.com/tutorial/2017/05/27/how-to-configure-mailgun-to-send-emails-in-a-django-app.html

**Comment by lifenautjoe** [comment]
Argh this would have saved me tons of time... Thanks you both and please @BradWhittington , add a notice that this is no longer mantained/supported.

**Comment by BradWhittington** [comment]
There's two notices on the repo directing people to use django-anymail, but I've removed it from pypi. Apologies for the inconvenience.
